package com.sistemadeoperaciones.notifications.enums;

public enum NotificationType {
    OPERATION_CREATED,
    PAYMENT_SUBMITTED,
    PAYMENT_TYPE_CHANGED,
    PAYMENT_VALIDATED,
    PAYMENT_REJECTED,
    OPERATION_STATUS_CHANGED,
    COMMISSION_PAID,
    CASH_RETURN_REQUESTED,
    CHEQUE_CASH_COLLECTION_ASSIGNED,
    CHEQUE_CASH_COLLECTION_RETURNED,
    CHEQUE_CASH_COLLECTION_WITHDRAWN,
    CHEQUE_CASH_COLLECTION_COMPLETED,
    // Parcialidades de retorno
    RETURN_INSTALLMENT_SCHEDULED,
    RETURN_INSTALLMENT_CODE_AVAILABLE,
    RETURN_INSTALLMENT_DELIVERED,
    RETURN_INSTALLMENT_COMPLETED,
    RETURN_INSTALLMENT_CANCELLED,
    RETURN_REQUEST_COMPLETED,
    SYSTEM_ALERT
}
