package com.sistemadeoperaciones.pagos.enums;

public enum OperationStatus {
    PENDIENTE_VALIDACION,
    INGRESO_PARCIAL,
    VALIDADA,
    RECHAZADA,
    RETORNO_PARCIAL_SOLICITADO,
    RETORNO_TOTAL_SOLICITADO,
    RETORNO_PARCIAL_ENTREGADO,
    RETORNADA,
    COMPLETADA
}